version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    # Disable the steady stream of version updates for actions; only notify about security updates.
    open-pull-requests-limit: 0
