# Documentation for this configuration file can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/cfg.html

targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" }
]

# See https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html.
[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
]

# See https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html.
[bans]
multiple-versions = "deny"
wildcards = "allow"

# Skip some multiple-versions checks, until they can be fixed.
skip = [
     # Transitive dependencies `libloading` and `log` depend on different versions of `cfg-if`;
     # remove once fixed upstream.
    { name = "cfg-if" },
]
