name: Make build for Analizers drop

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Check upstream C library
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build C library
      run: python buildall.py -pt -v
