# Ci workflow to be triggered for every pull-request and push
name: "CI ITT PYTHON"

on:
  push:
    branches: ["**"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    runs-on: ['${{matrix.os}}']

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: install ittapi
        run: |
          cd python
          python3 -m pip install .

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    runs-on: ['${{matrix.os}}']
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: run unit-test
        run: |
          cd python
          python3 -m unittest discover -s utest -t utest
