name: Test the workflow for testpypi publishing
on: workflow_dispatch
permissions:
  contents: read

jobs:
  # build wheels only for cpython versions 3.8-3.12 on linux and windows 64-bits
  python_build:
    name: Build ittapi wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cibw_skip_args: "*_i686 *-musllinux_* cp313-*"
          - os: windows-latest
            cibw_skip_args: "*-win32 *_i686 cp313-*"
    steps:
      - name: Checkout sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install cibuildwheels
        run: python -m pip install cibuildwheel==2.20.0
      - name: Build ittapi python wheels
        run: python -m cibuildwheel python --output-dir python_dist/
        env:
          CIBW_BUILD: cp3*
          CIBW_SKIP: ${{ matrix.cibw_skip_args }}
      - name: Upload artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: build-artifacts-python-${{ matrix.os }}
          path: python_dist*/**

  # upload the built wheels to test-pypi
  upload_to_pypi:
    name: Upload the wheel files to test-pypi
    runs-on: ubuntu-latest
    needs: python_build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          pattern: build-artifacts-*
          merge-multiple: true
      - name: List wheel files
        run: find -name *.whl
      - name: Publish the package to test-pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: python_dist
